### ISSUE TITLE
Is there list of differences with enricostara/telegram.link ?

### ISSUE THREAD

**Issue by FragsterAt** [goodmind/telegram.link#25]
subj

**Comment by goodmind** [comment]
There is no list, but most of the differences is primarily in `telegram-tl-node`.
I am not commiting new commits because friend of mine is porting`webogram` (i.e. removing angularjs related code).

Because there a lot of bugs in `telegram-mt-node` which prevents us connecting to another datacenters to download photos of users (server just responds with a lot of 404s)

**Comment by FragsterAt** [comment]
>  is porting webogram (i.e. removing angularjs related code).

result of this porting would be in this project, or somewhere else?
would it be usable for server side apps (node.js)?

**Comment by goodmind** [comment]
I don't know for now
